# Generated by Django 2.0.4 on 2019-04-24 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('dni', models.IntegerField()),
                ('nro_registro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('sector', models.CharField(max_length=250)),
                ('nro_aula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='materia',
            field=models.ManyToManyField(to='aulas.Materia'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.Materia'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ManyToManyField(to='aulas.Carrera'),
        ),
    ]
