# Generated by Django 2.2 on 2019-04-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
