# Generated by Django 2.2 on 2019-05-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_remove_disponibilidad_ocupado'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidad',
            name='dia',
            field=models.IntegerField(default=0),
        ),
    ]
